# Generated by Django 6.0.6 on 2026-07-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0002_mpesatransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Mpesa', 'M-Pesa')], default='Cash', max_length=20),
        ),
    ]
